energy-savings-scheme/openfisca_nsw_safeguard

openfisca_nsw_safeguard/tests/PDRS/PDRS_WH1/test_PDRS_WH1_meets_requirements.yaml, openfisca_nsw_safeguard/variables/PDRS_activities/PDRS_WH1/PDRS_WH1_equipment_requirements.py, openfisca_nsw_safeguard/variables/PDRS_activities/PDRS_WH1/PDRS_WH1_implementation_requirements.py
Pull request to merge PDRS-WH1 into the Master branch. This branch includes WH1 activity requirements as well as tests.
=> PDRS WH1 Tests

openfisca_nsw_safeguard/variables/PDRS_activities/PDRS_WH1/PDRS_WH1_eligibility_requirements.py
Updating WH1 with recent rule changes as per the [rule change tracking Jira board ](https://essnsw.atlassian.net/browse/RCT-4)  Have passed and run tests at my end.
=> Removed Gas from WH1 equipment as per rule change

openfisca_nsw_safeguard/tests/ESS_PDRS_base_eligibility, openfisca_nsw_safeguard/variables/ESS_PDRS_base_eligibility.py, openfisca_nsw_safeguard/variables/ESS_general/ESS_general_criteria.py, openfisca_nsw_safeguard/variables/PDRS_general/PDRS_overall_eligibility.py
The PDRS__removing_or_replacing variable was missing - just added it in
=> Adding removing or replacing variable

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/activity_eligibility/HVAC2_activity_eligibility_parameters.py
Sorting order and conditionals for Base scheme eligibility and HVAC2 eligibility
=> Sorting order

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2/HVAC2_PRC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1/WH1_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_PRC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/WH1_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/WH1_ESC_variables.py
ESC calculations, variables and tests
=> Wh1 calculation

openfisca_nsw_safeguard/parameters/ESS/ESS_general/Postcode_zones_air_source_heat_pumps.yaml
This is the table we need to pull the postcode zone and then HP Gas and HP Elec
=> Postcode zones for air source heat pumps

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/activity_eligibility/HVAC2_eligibility.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_PRC_variables.py, openfisca_nsw_safeguard/variables/ESS_general/ESS_site_type.py, openfisca_nsw_safeguard/variables/PDRS_general/PDRS_number_of_certificates.py
The display question adjustments and sorting order for the HVAC2 certificate calculation page
=> Hvac2 cleanup

openfisca_nsw_safeguard/parameters/ESS/ESS_general/table_A27_AS3823.4_climate_zone_by_postcode.yaml
Table A27 - hot, average, cool zones by postcode
=> Table a27 zones by postcode

openfisca_nsw_safeguard/parameters/ESS/ESS_general/Postcode_zones_air_source_heat_pumps.yaml
Removed some extra spacing that was in the table (tests passing now)
=> Postcode zones cleanup

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_ESC_variables.py
HVAC1 ESC strings to ints cleanup
=> strings to ints

openfisca_nsw_safeguard/parameters/ESS/ESS_general/table_A27_4_climate_zone_by_postcode.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_PRC_variables.py
All tests are now passing: Hurrah!
=> HVAC1 PRCs all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py
Extra base eligibility tests are ready to merge.
=> Base scheme tests

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_PRC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_PRC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/WH1_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/WH1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/WH1_PRC_variables.py
=> Display labels for data inputs

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1/WH1_PRC_calculation.yaml
Added a test against my manual PRC calculations for Ecogenica, all tests passing
=> WH1 PRCs test for Ecogenica all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2/RF2_ESC_calculation.py
=> HVAC1 PRC Calculation for Coolmaster

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_ESC_calculation.yaml
An added test while testing the SEER / TCEC / Equation D16.2 units. All tests passing.
=> Added HVAC1 test Mitsubushi

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_ESC_calculation.yaml
Added an ESC test for Fujitsu to confirm 0 ESCs
=> HVAC2 Fujitsu test - all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS2/SYS2_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS2/SYS2_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/certificate_estimation/SYS2_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/certificate_estimation/SYS2_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/certificate_estimation/SYS2_PRC_calculation.py
Added the PRC new vs replacement - all tests passing
=> Sys2 new replacement all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS1/SYS1_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS1/SYS1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS1/certificate_estimation/SYS1_PRC_calculation.py
All tests are passing but note there were two formulas in here as multiplication rather than division
=> SYS1 testing - note two formula mistakes

openfisca_nsw_safeguard/parameters/PDRS/pool_pumps/table_sys2_2.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS2/SYS2_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/certificate_estimation/SYS2_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/certificate_estimation/SYS2_PRC_variables.py
All tests passing, values corrected in table
=> SYS2 table SYS2.2 values corrected

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS1/SYS1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS1/certificate_estimation/SYS1_PRC_calculation.py
there was a typo early on in the formula which was throwing everything off
=> Sys1 abb test all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/RF1/RF1_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/RF1/RF1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF1/certificate_estimation/RF1_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF1/certificate_estimation/RF1_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF1/certificate_estimation/RF1_PRC_calculation.py
=> Rf1 storage eligibility

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2/HVAC2_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_ESC_variables.py
The tables for ESCs for HVAC1 and HVAC2 were swapped. All tests passing.
=> HVAC1 HVAC2 table fix

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS1/SYS1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS1/certificate_estimation/SYS1_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS1/certificate_estimation/SYS1_PRC_calculation.py
Fixes rated output of 185. All tests passing.
=> Sys1 cleanup

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS1/certificate_estimation/SYS1_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/certificate_estimation/SYS2_PRC_variables.py
Clean up on helper text for eligibility guidance on user inputs
=> SYS1 and SYS2 helper text

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py
The first of our Eligibility check branches
=> Base eligibility check

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py
Swapped Q9 and Q10 as per our chat
=> Sorting cleanup 9 and 10

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2/HVAC2_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_ESC_variables.py
Another test - all tests passing
=> Panasonic testing all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2/HVAC2_PRC_calculation.yaml
=> Test cleanup

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/activity_eligibility/HVAC1_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/activity_eligibility/HVAC2_activity_eligibility_parameters.py
HVAC grammar cleanups for Jamie
=> Grammar cleanups

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_PRC_calculation.py
Correction to the usage factor on HVAC1
=> HVAC1 usage factor correction

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/activity_eligibility/HVAC2_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2/activity_eligibility/RF2_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/activity_eligibility/WH1_activity_eligibility_parameters.py
little bits and pieces all over the codebase
=> Hvac grammar cleanups

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2/HVAC2_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_ESC_calculation.py
=> Mitsubishi esc test added Daikin test

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2/activity_eligibility/RF2_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/activity_eligibility/SYS2_activity_eligibility_parameters.py
A cleanup and reorder of questions in RF2
=> Rf2 order cleanup

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS2/SYS2_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/certificate_estimation/SYS2_PRC_variables.py
Updated the codebase with the ESCs that are eligible for this activity (input power). All tests passing.
=> ESC clean up on input power

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/activity_eligibility/HVAC1_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/activity_eligibility/HVAC2_activity_eligibility_parameters.py
Small copy update on the climate zone dropdowns on HVAC 1 & 2
=> Copy update on climate zone dropdown

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS2/SYS2_replacement_final_activity_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/activity_eligibility/SYS2_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/activity_eligibility/SYS2_eligibility.py
This branch has both ACP flow changes on base eligibility and also SYS2 formula cleanup that we discussed. These tests are passing.
=> Acp flow change

openfisca_nsw_safeguard/parameters/ESS/HEER/table_D16_3.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_ESC_calculation.py
This turned out to be a small typo on one of the tables (D16.3). The typo has been fixed and tests are passing.
=> Hvac1 actron air test

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py
Updated the date dropdown options: all tests passing.
=> Date dropdown groupings updated: all tests passing

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/activity_eligibility/HVAC1_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/activity_eligibility/HVAC2_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/activity_eligibility/WH1_activity_eligibility_parameters.py
=> Changed spacing on clauses over to break

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py
A tiny fix to correct the Planned Activity date dropdown to not eligible
=> Corrected planned activity to not eligible

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/activity_eligibility/SYS2_eligibility.py
Added some clean ups here and there (removed prints and an implementation date cleanup), all tests passing
=> Eligibility clause added to Base_removing_or_replacing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_PRC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/certificate_estimation/WH1_PRC_calculation.py
Added the postcode - network loss factor. All tests passing
=> HVAC1 Postcode to network loss factor added

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2/HVAC2_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2/HVAC2_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_PRC_variables.py
Added the postcode - network loss factor. All tests passing
=> Added Network Loss Factor to HVAC2 all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/RF1/RF1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF1/certificate_estimation/RF1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF1/certificate_estimation/RF1_PRC_variables.py
=> RF1 postcode to network loss factor update

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/activity_eligibility/SYS2_activity_eligibility_parameters.py
A small question update for pool pumps
=> Question updated

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py
Small adjustment on the clause for date eligibility
=> Removed extra clause on date requirements

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/activity_eligibility/WH1_activity_eligibility_parameters.py
=> updated the WH1 install and replacement clauses

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py
=> Date eligibility fixed for before April 1 2022

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/ESS_PDRS_base_scheme/ESS_PDRS_base_eligibility_variables.py
Clause update for Planned Activity: all tests passing. Please push up to nonprod and secondary.
=> Updated clause for planned activity

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/activity_eligibility/HVAC1_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2/activity_eligibility/RF2_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/activity_eligibility/SYS2_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/activity_eligibility/WH1_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/General_Appliances/AC_variables/AC_common.py, openfisca_nsw_safeguard/variables/High_Efficiency_Appliances_Business (HEAB)/Heat_Pumps/ESS_replace_boiler_or_water_heater_with_air_source_heat_pump/ESS_replace_boiler_or_water_heater_with_air_source_heat_pump_equipment_requirements.py, openfisca_nsw_safeguard/variables/High_Efficiency_Appliances_Business (HEAB)/Heat_Pumps/ESS_replace_boiler_or_water_heater_with_air_source_heat_pump/ESS_replace_boiler_or_water_heater_with_air_source_heat_pump_implementation_requirements.py, openfisca_nsw_safeguard/variables/PDRS_activities/PDRS_WH1/PDRS_WH1_equipment_requirements.py, openfisca_nsw_safeguard/variables/PDRS_activities/PDRS_WH1/PDRS_WH1_implementation_requirements.py
Updated end-user with End-User. Please deploy to nonprod and secondary
=> Replaced end-user with End-User

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_installation_final_activity_eligibility.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1/WH1_installation_final_activity_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/activity_eligibility/HVAC1_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/activity_eligibility/HVAC1_eligibility.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/activity_eligibility/WH1_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/activity_eligibility/WH1_eligibility.py
Cleaned up WH1 (all tests passing) and added HVAC1 ACP engaged into the eligibility criteria
=> Hvac1 acp engaged

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_ESC_variables.py
Missed some of the GEMS language changes
=> GEMS language cleanup all tests passing

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS1/certificate_estimation/SYS1_ESC_variables.py
Small typo change, all tests passing
=> Changed hz to Hz

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF1/activity_eligibility/RF1_activity_eligibility_parameters.py
Small copy change, all tests passing
=> Added fridge storage capacity requirement

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS1/certificate_estimation/SYS1_ESC_variables.py
=> Dropped case down on rated output and frequency

openfisca_nsw_safeguard/parameters/ESS/HEER/table_D16_5.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_ESC_variables.py
This is the branch I've been working on
=> Testing for Carrier bug

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D17/D17_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D19/D19_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D17/certificate_estimation/D17_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D19/certifcate_estimation/D19_ESC_variables.py
Adds the postcode - BCA - heat pump zone flow into D17 and D19 certificate estimations
=> Add postcode hp flow

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1/WH1_PRC_calculation.yaml
Just added one test to check that postcode 2000 is returning heat pump zone 3 (which it is)
=> Added one test for postcode 2000

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D18/D18_installation_final_activity_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D18/activity_eligibility/D18_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D18/activity_eligibility/D18_eligibility.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D19/activity_eligibility/D19_activity_eligibility_parameters.py
=> D18 activity eligibility plus typo fix D17 D19

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS1/activity_eligibility/BESS1_activity_eligibility_parameters.py
BESS1 Activity Eligibility Parameters
Testing not completed, Kate please review :)
=> BESS1 eligibility

openfisca_nsw_safeguard/parameters/PDRS/table_A6_firmness_factor.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/BESS1/BESS1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS1/certificate_estimation/BESS1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS1/certificate_estimation/BESS1_PRC_variables.py
=> Bess1 certificate calculation

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/BESS1/BESS1_PRC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/BESS2/BESS2_PRC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_PRC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2/HVAC2_PRC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/RF1/RF1_PRC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/RF2/RF2_PRC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS1/SYS1_PRC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS2/SYS2_PRC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1/WH1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS1/certificate_estimation/BESS1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS2/certificate_estimation/BESS2_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF1/certificate_estimation/RF1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF1/certificate_estimation/RF1_PRC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2/certificate_estimation/RF2_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS1/certificate_estimation/SYS1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/certificate_estimation/SYS2_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1/certificate_estimation/WH1_PRC_calculation.py
adding new variable Peak demand annual savings
=> Peak demand annual savings All Tests Passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2/HVAC2_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2/HVAC2_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_PRC_calculation.py
HVAC2 ESS and PDRS savings on same branch. All tests passing.
=> HVAC2 ESS and PDRS savings all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/BESS1/BESS1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS1/certificate_estimation/BESS1_PRC_calculation.py
Updated BESS1_peak_demand_annual_savings  -  All tests passing
=> Bess1 ess savings

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/BESS2/BESS2_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS2/certificate_estimation/BESS2_PRC_calculation.py
BESS 2 peak demand annual savings - all tests passing
=> Bess2 ess savings

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D19/D19_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D19/certificate_estimation/D19_ESC_calculation.py
=> D19 ess savings

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/RF1/RF1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF1/certificate_estimation/RF1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF1/certificate_estimation/RF1_PRC_variables.py
This includes an updated PRC calculation to add in number of fridges
=> RF1 peak demand savings all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D18/D18_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D18/certificate_estimation/D18_ESC_calculation.py
Added D18 deemed_activity_electricity_savings all tests passing successfully.
=> D18 ESS savings

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1/WH1_ESC_calculation.yaml
Added extra tests to check calculations for Iris testing the UI. All tests passing
=> WH1 ESS annual savings tests all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_ESC_calculation.yaml
Building extra tests for UI testing
=> HVAC1 added extra tests all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS1/certificate_estimation/SYS1_PRC_calculation.py
Retesting HVAC1, and also cleaned up SYS1 prints while I was at it
=> HVAC1 all tests passing SYS1 prints removed

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_PRC_calculation.py
This adds a check for PRCs, if 0 PRCs, then return 0 annual savings. Please double check this coding doesn't interfere with the UI before I go ahead and add it to other activities.
=> HVAC1 PRCs vs savings check all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_PRC_calculation.py
This is our HVAC1 experiment: I've added regional network factor and lifetime value into the energy savings so that we can test it out on the UI. All tests passing.
=> Hvac1 experiment savings all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1/HVAC1_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1/certificate_estimation/HVAC1_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2/certificate_estimation/RF2_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2/certificate_estimation/RF2_PRC_calculation.py
This fixes TCEC or cooling / THEC or heating bug. All tests passing
=> HVAC1 all tests passing RF2 prints removed

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D18/D18_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D18/certificate_estimation/D18_ESC_calculation.py
this PR fixes a mistake in the D18 energy savings code
=> energy savings table fix all tests passing

openfisca_nsw_safeguard/parameters/ESS/HEER/table_D20_1.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D19/D19_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D20/D20_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D20/certificate_estimation/D20_ESC_calculation.py
There were some wrong values coded in the D20 tables. I have fixed these and all tests are passing as expected.
=> Fixed D20 tables all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/RF1/RF1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF1/certificate_estimation/RF1_PRC_variables.py
this PR fixes number of fridges for PRCs which was calculating twice
=> number fridges fix all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS1/SYS1_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS1/certificate_estimation/SYS1_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS1/certificate_estimation/SYS1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/certificate_estimation/SYS2_ESC_calculation.py
two little fixes in here, all tests passing now
=> SYS1 fix all tests passing

openfisca_nsw_safeguard/parameters/ESS/HEER/table_D20_1.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D20/D20_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/RF2/RF2_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/RF2/RF2_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D20/certificate_estimation/D20_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2/certificate_estimation/RF2_ESC_calculation.py
this PR fixes some incorrect table values - all tests passing
=> D20 values updated all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/F17/F17_installation_final_activity_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/F17/activity_eligibility/F17_eligibility.py
There was an extra variable in the final formula which has been removed and all tests are passing
=> Removed extra variable from final formula all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/F17/F17_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS1/certificate_estimation/BESS1_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/F17/certificate_estimation/F17_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/F17/certificate_estimation/F17_ESC_variables.py
All F17 all tests passing.
BESS1 - changes made to add "l" in eligibility
=> F17 certificate

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D19_ESSJun24/D19_ESSJun24_installation_final_activity_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D19_ESSJun24/activity_eligibility/D19_ESSJun24_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D19_ESSJun24/activity_eligibility/D19_ESSJun24_eligibility.py
D19 ESSJun24 Eligibility All tests passing
=> D19 ess jun24 eligibility

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D19_ESSJun24/D19_ESSJun24_ESC_calculation.yaml
Adds one new test and cleans up the comments on another
=> Extra testing all tests passing

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D17_ESSJun24/D17_ESSJun24_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D17_ESSJun24/certificate_estimation/D17_ESSJun24_ESC_calculation.py
This PR fixes a broken table reference in D17
=> Fixed broken table reference all tests passing

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D17_ESSJun24/activity_eligibility/D17_ESSJun24_activity_eligibility_parameters.py
My first push to develop branch!
This PR updates the question we ask for D17 ESS Jun 24 (all tests passing)
=> D17 copy update

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/D20_ESSJun24/D20_ESSJun24_ESC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/D20_ESSjun24/certificate_estimation/D20_ESSJun24_ESC_calculation.py
This PR fixes if Bs and Be are zero, then return 0 ESCs. All tests passing.
=> D20 zero esc fix

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/RF2_F1.2_ESSJun24/RF2_F1_2_installation_final_activity_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2_F1.2_ESSJun24/activity_eligibility/RF2_F1.2_ESSJun24_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2_F1.2_ESSJun24/activity_eligibility/RF2_F1.2_ESSJun24_eligibility.py
This PR adds a payment question to F1.2. All tests passing.
=> F1.2 payment q all tests passing

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2_F1.2_ESSJun24/activity_eligibility/RF2_F1.2_ESSJun24_activity_eligibility_parameters.py
This PR updates the sorting order for the questions (there were to #6). All tests passing.
=> F1.2 payment q move

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2_F1.2_ESSJun24/activity_eligibility/RF2_F1.2_ESSJun24_activity_eligibility_parameters.py
This PR is another attempt at getting the spacing right. The indents were reading badly so I have removed them and left the line breaks in.
=> F1.2 clause spacing

openfisca_nsw_safeguard/tests/ESS/ESS_NABERS/calculations/ESS_NABERS_annual_electricity_savings.yaml, openfisca_nsw_safeguard/tests/ESS/ESS_NABERS/calculations/ESS_NABERS_electricity_savings.yaml, openfisca_nsw_safeguard/tests/ESS/ESS_NABERS/calculations/ESS_NABERS_forward_electricity_savings.yaml, openfisca_nsw_safeguard/tests/ESS/ESS_NABERS/eligibility/ESS_NABERS_eligibility_by_date.yaml, openfisca_nsw_safeguard/tests/ESS/ESS_NABERS/eligibility/ESS_NABERS_is_eligible.yaml, openfisca_nsw_safeguard/tests/ESS/ESS_general/ESS_number_of_ESCs.yaml
This PR fixes all of the NABERS errors - all tests passing
=> Nabers fixes

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2_F1.2_ESSJun24/activity_eligibility/RF2_F1.2_ESSJun24_activity_eligibility_parameters.py
Updated payment question clauses from ESS Clause 9.9.1k to 9.9.1E
=> F1.2 eligibility payment clause update test pass

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/WH1_F16_electric_PDRSAug24_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/WH1_F16_electric_PDRSAug24_PRC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/WH1_F16_electric_PDRSAug24_installation_final_activity_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/activity_eligibility/WH1_F16_electric_PDRSAug24_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/activity_eligibility/WH1_F16_electric_PDRSAug24_eligibility.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/certificate_estimation/WH1_F16_electric_PDRSAug24_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/certificate_estimation/WH1_F16_electric_PDRSAug24_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/certificate_estimation/WH1_F16_electric_PDRSAug24_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/certificate_estimation/WH1_F16_electric_PDRSAug24_PRC_variables.py
This PR adds the new WH1 PDRS folders, as well as the capacity factor. All tests are passing
=> Wh1 pdrs capacityfactor

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/WH1_F16_electric_PDRSAug24_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/certificate_estimation/WH1_F16_electric_PDRSAug24_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/certificate_estimation/WH1_F16_electric_PDRSAug24_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/certificate_estimation/WH1_F16_electric_PDRSAug24_PRC_variables.py
This PR adds in the new PDRS Rule 2 value of volumetric capacity. All tests passing.
=> Wh1 minimum volume

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/WH1_F16_electric_PDRSAug24_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/certificate_estimation/WH1_F16_electric_PDRSAug24_PRC_variables.py
This PR corrects the code for adding in a new value of volumetric capacity into WH1 PRCs. All tests passing.
=> Wh1 volume fix

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1_PDRSAug24/certificate_estimation/HVAC1_PDRSAug24_PRC_calculation.py
This PR updates the map copy to put the url at the end of the sentence
=> Hvac1 experiment copy update

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS2/SYS2_replacement_final_activity_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2_PDRSAug24/activity_eligibility/SYS2_PDRSAug24_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2_PDRSAug24/activity_eligibility/SYS2_PDRSAug24_eligibility.py
This PR has the SYS2 eligibility updates. All tests passing.
=> D5 eligibility pdrs rule2

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/BESS1_PDRSAug24/BESS1_PDRSAug24_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS1_PDRSAug24/certificate_estimation/BESS1_PDRSAug24_PRC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS1_PDRSAug24/certificate_estimation/BESS1_PDRSAug24_PRC_variables.py
All tests are passing for BESS1 PDRSAug24 Certificate.
=> BESS1 PDRSAug24 Certificate

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS1/activity_eligibility/SYS1_activity_eligibility_parameters.py
A tiny clause update, all tests passing
=> Sys1 rated output clause

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS2_PDRSAug24/SYS2_PDRSAug24_PRC_calculation.yaml
This is just a small PR to add some extra tests. All tests passing.
=> Master tester added tests

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2/activity_eligibility/SYS2_activity_eligibility_parameters.py
Updated eligibility clause, all tests passing
=> Sys2 clause update

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS2_PDRSAug24/SYS2_PDRSAug24_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS2_PDRSAug24/SYS2_PDRSAug24_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2_PDRSAug24/certification_estimation/HVAC2_PDRSAug24_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2_PDRSAug24/certificate_estimation/SYS2_PDRSAug24_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2_PDRSAug24/certificate_estimation/SYS2_PDRSAug24_PRC_calculation.py
=> Sys2 zero if no data

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/WH1_F16_electric_PDRSAug24_installation_final_activity_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/activity_eligibility/WH1_F16_electric_PDRSAug24_activity_eligibility_parameters.py
WH1 Eligibility uppercase change all test passing.
=> Wh1 uppercase 

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/WH1_F16_electric_PDRSAug24_installation_final_activity_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/activity_eligibility/WH1_F16_electric_PDRSAug24_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/activity_eligibility/WH1_F16_electric_PDRSAug24_eligibility.py
This PR adds in new variables for ESC and PRC storage. All tests passing.
=> Wh1 esc prc eligible

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/SYS2/SYS2_replacement_final_activity_eligibility.yaml
This PR fixes one SYS test. All tests passing
=> Sys2 test fix

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1_PDRSAug24/HVAC1_PDRSAug24_PRC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2_PDRSAug24/HVAC2_PDRSAug24_PRC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/WH1_F16_electric_PDRSAug24/WH1_F16_electric_PDRSAug24_installation_final_activity_eligibility.yaml
This PR fixes some broken tests - all tests now passing
=> Tests cleanup

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2_PDRSAug24/HVAC2_PDRSAug24_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2_PDRSAug24/certification_estimation/HVAC2_PDRSAug24_PRC_calculation.py
This PR updates the usage factor to the correct one and updates the test results. All tests passing.
=> Hvac2 samsung new test

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2_PDRSAug24/HVAC2_PDRSAug24_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2_PDRSAug24/HVAC2_PDRSAug24_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2_PDRSAug24/certification_estimation/HVAC2_PDRSAug24_ESC_calculation.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2_PDRSAug24/certification_estimation/HVAC2_PDRSAug24_ESC_variables.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2_PDRSAug24/certification_estimation/HVAC2_PDRSAug24_PRC_calculation.py
All tests passing - updated TCEC and THEC - updating residential to commercial
=> HVAC2 annual check

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC2_PDRSAug24/HVAC2_PDRSAug24_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC2/certificate_estimation/HVAC2_PRC_variables.py
This PR adds an extra set of tests for one of the Mistubishi models. All tests passing. I have requested Alisha, Robbie and Kus on the PR review for practice.
=> Added testing HVAC2 all tests passing

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS1_V5Nov24/activity_eligibility/BESS1_V5Nov24_activity_eligibility_parameters.py
* Adds an apostrophe into the copy on question 8
* No technical changes
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1754
None
[DG22-1754]: https://essnsw.atlassian.net/browse/DG22-1754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1754] BESS1 copy fix

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1_PDRSAug24/HVAC1_PDRSAug24_ESC_calculation.yaml, openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/HVAC1_PDRSAug24/HVAC1_PDRSAug24_PRC_calculation.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/HVAC1_PDRSAug24/certificate_estimation/HVAC1_PDRSAug24_PRC_calculation.py
* A set of tests on a specific air conditioner model as requested by an ACP
* Added tests to HVAC1 ESCs and PRCs
None
None
=> [ACP check] Extra tests for LG model

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/BESS1_PDRSDec24/BESS1_PDRSDec24_installation_final_activity_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS1_PDRSDec24/activity_eligibility/BESS1_PDRSDec24_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS1_PDRSDec24/activity_eligibility/BESS1_PDRSDec24_eligibility.py
* Updates BESS1 inverter questions
* Updates sorting order for BESS1 questions
* Changed second BESS1 inverter question (Q14) back to a boolean from an enum
• Updated question sorting order for Q9 - 15
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1840
None
[DG22-1840]: https://essnsw.atlassian.net/browse/DG22-1840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1840] BESS1 eligibility inverter questions

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/F16_electric_PDRSDec24/activity_eligibility/F16_electric_PDRSDec24_activity_eligibility_parameters.py
* Updates the default value on F16 storage questions
* Changed Q11 default value to true
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1840
None
[DG22-1840]: https://essnsw.atlassian.net/browse/DG22-1840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1840] F16 storage question cleanup

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS1_PDRSDec24/activity_eligibility/BESS1_PDRSDec24_activity_eligibility_parameters.py
* Updates copy on BESS1 eligibility question 18
* This is a copy change only
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1839
None
[DG22-1839]: https://essnsw.atlassian.net/browse/DG22-1839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1839] BESS1 eligibility updated question

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/BESS2_V5Nov24/activity_eligibility/BESS2_V5Nov24_activity_eligibility_parameters.py
* Adjust copy at Q4 eligibility clause
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2396
- None 
- None
- None
[DG22-2396]: https://essnsw.atlassian.net/browse/DG22-2396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-2396] BESS2 rule 3 update 

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2_F1.2_ESSJun24/activity_eligibility/RF2_F1.2_ESSJun24_activity_eligibility_parameters.py
* adjust copy at question number 7 in eligibility
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2386
- None 
- None
- None
[DG22-2386]: https://essnsw.atlassian.net/browse/DG22-2386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-2386] F1.2/RF2 Update eligibility clause

openfisca_nsw_safeguard/tests/ESS_PDRS_Estimator/F16_electric_PDRSDec24/F16_electric_PDRSDec24_installation_final_activity_eligibility.yaml, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/F16_electric_PDRSDec24/activity_eligibility/F16_electric_PDRSDec24_activity_eligibility_parameters.py, openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/F16_electric_PDRSDec24/activity_eligibility/F16_electric_PDRSDec24_eligibility.py
Added 2 new Variables (Questions 5 & 6).
(For UI Update) 
If Q5 is No, go to Q7. 
If Q5 is Yes, go to Q6.  (Please refer to Miro:  https://miro.com/app/board/uXjVPXwFzQ0=/?moveToWidget=3458764621239428494&cot=14) 
Also Question 13, default_value changed to False. 
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2467
- None
- None
[DG22-2467]: https://essnsw.atlassian.net/browse/DG22-2467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F16 Electric eligibility: update with ESS 2025 requirements

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/F16_electric_PDRSDec24/activity_eligibility/F16_electric_PDRSDec24_activity_eligibility_parameters.py
* updated the eligibility clause in F16_electric_PDRSDec24__certified and F16_electric_PDRSDec24__storage_volume to include the word "that" in the clause.
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2467
- None 
- None
- None
[DG22-2467]: https://essnsw.atlassian.net/browse/DG22-2467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F16 Electric Eligibility Clause Update

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/SYS2_PDRSAug24/activity_eligibility/SYS2_PDRSAug24_activity_eligibility_parameters.py
* Updated the eligibility clause in for Q6
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2439
- None 
- None
- None
[DG22-2439]: https://essnsw.atlassian.net/browse/DG22-2439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> D5/SYS2 Eligibility Payment Clause Fix

openfisca_nsw_safeguard/variables/ESS_PDRS_Estimator/RF2_F1.2_ESSJun24/activity_eligibility/RF2_F1.2_ESSJun24_activity_eligibility_parameters.py
* Updated the eligibility clause in for Q8 and Q9
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2548
- None 
- None
- None
=> Refrigerated Cabinets eligibility: Minor fixes and changes for eligibility answers
